name: First Workflow
on: workflow-dispatch
jobs:
first-job:
        runs-on: ubuntu-latest
        steps:
        -name: Print greeting
        runs: echo "Hello World"
        -name: Printing goodbye
        run: echo "Done-bye!"
         
